version: "3.7"
services:
  web:
    image: dirui/mrpp-public
    environment:
      - NGINX_PORT=80
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.public-secure.entrypoints=websecure"
      - "traefik.http.routers.public-secure.rule=Host(`public.mrpp.com`)"
#    ports:
#      - "8080:80"
networks:
    proxy:
      external: true